# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          path: ./pub/
      - name: Send Command
        run: |
          $iotConnString  = "${{secrets.IOTCONNECTIONSTRING}}"
          $deviceId = "MrBrick"

          Import-Module ".\.github\workflows\dll\Microsoft.Azure.Devices.dll" -Verbose

          $stringArray = $()
          $added_files = ${{ steps.changed-files.outputs.all_changed_files }} 
          $added_files
          $stringArray += ${{ steps.changed-files.outputs.all_changed_files }} 
          $stringArray.count
          $content = Get-Content -Path $stringArray

          $Speed = 20
          $commands = @{}
          foreach($line in $content){
              $cmd  = $line.Replace(" ","").split(":")[0]
              $value = $line.Replace(" ","").split(":")[1]
              switch($cmd){
                  "left" {
                      $commands["leftDuration"] = $value 
                      $commands["leftSpeed"] = $Speed * 10 # 100% speed
                  }
                "right" {
                      $commands["rightDuration"] = $value 
                      $commands["rightSpeed"] = $Speed * 10 # 100% speed
                  }
              }
          }
          $messageString = $commands | convertto-json
          $cloudClient = [Microsoft.Azure.Devices.ServiceClient]::CreateFromConnectionString($iotConnString)
          $messagetosend = [Microsoft.Azure.Devices.Message]([Text.Encoding]::ASCII.GetBytes($messageString))
          $cloudClient.SendAsync($deviceId, $messagetosend)
        shell: powershell
